### ISSUE TITLE
Star Duplication Glitch

### ISSUE THREAD

**Issue by Motokuro** [riddbtw/kovaaks-playlists#3]
If you were to "star" a playlist, and that playlist's "filename" doesn't match its TRUE hardcoded "playlistName" then Kovaaks will duplicate said playlist into two separate files one retaining the original file name, and the other renamed to the hardcoded "playlistName," both of which can then be "starred" or "unstarred" indepentently, without you knowing which file is the original or which file is the duplicate due to them both displaying the hardcoded "playlistName" in-game. Also If you were to delete the new Kovaaks created file, which is indistinguishable from the original file in-game, then the whole process repeats itself. With all this being said, I'd recommend that you'd either rename your file names to the hardcoded "playlistName" or vice-versa.

Exaple: 
File Name: "EerieCold_-_Static.json"
Hardcoded Name: "playlistName": "EerieCold - Static"

The file type does not matter AKA .json or .plo

**Comment by riddbtw** [comment]
interesting find, thanks i was wondering why that was happening...i'll match them up.  most likely going to just change the json file scen name to the actual filename.  Problem is I'll have to look for this for everyone new playlist I import in case the playlist author did this...thanks for raising up tho, i may bring this up to kovaak too.
